name: Daily Briefing

on:
  schedule:
    # 9:30 UTC = 4:30am CT (winter) / 3:30am CT (summer)
    - cron: '30 9 * * 1-5'

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install yfinance --quiet

      - name: Generate daily briefing
        env:
          BARCHART_API_KEY:  ${{ secrets.BARCHART_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: python scripts/generate_daily.py

      - name: Commit daily.json
        run: |
          git config user.name  "AGSIST Daily Bot"
          git config user.email "noreply@agsist.com"
          git add data/daily.json
          git diff --cached --quiet && echo "No changes to commit" || \
            git commit -m "Daily briefing $(date -u +'%Y-%m-%d %H:%M UTC')"
          git push
